# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/SouthBitsLab

    - name: micro-ROS
      url-base: https://github.com/SouthBitsLab

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v4.1.0
      import: true

    - name: micro_ros_zephyr_module
      remote: micro-ROS
      repo-path: micro_ros_zephyr_module
      revision: jazzy
      path: micro_ros_zephyr_module

  self:
    path: app-manifest